name: quran_mvp
description: یک اپلیکیشن MVP ساده برای خواندن قرآن به زبان فارسی (بدون بک‌اند).
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/data/quran.json
